FROM openjdk:8u312-jdk
LABEL maintainer=oimaoyanio
# 设置环境变量
ENV SERVER_PORT 8080

ENV MYSQL_USERNAME root
ENV MYSQL_PASSOWRD ar352878987
ENV MYSQL_ADDRESS localhost
ENV MYSQL_PORT 3306

ENV REDIS_ADDRESS localhost
ENV REDIS_PORT 6379
ENV REDIS_PASSWORD ar352878987

ENV MAIL_USERNAME 1071352028@qq.com
ENV MAIL_PASSWORD wxmvjoivirfebfcc

ENV RABBITMQ_ADDRESS localhost
ENV RABBITMQ_PORT 5672
ENV RABBITMQ_USERNAME guest
ENV RABBITMQ_PASSWORD guest
# 复制到Docker Linux中的根目录下的QuickDevelop.jar
COPY target/*.jar /QuickDevelop-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/QuickDevelop-0.0.1-SNAPSHOT.jar"]