select dq_collection.collection_id,
       dq_collection.user_id,
       dq_collection.article_id,
       dq_collection.create_time,
       dq_collection.update_time,
       da.article_id,
       da.article_title,
       da.article_content,
       da.article_image,
       da.section_id,
       da.section_type_id,
       da.author_id,
       da.status,
       da.article_weight,
       da.create_time,
       da.update_time,
       ds.section_id,
       ds.section_name,
       ds.section_introduce,
       ds.section_logo,
       ds.section_background,
       ds.section_admin_user_id,
       ds.section_weight,
       ds.create_time,
       ds.update_time,
       dst.section_type_id,
       dst.section_type_name,
       dst.section_id,
       dst.section_type_weight,
       dst.section_type_mold,
       dst.section_type_network,
       dst.create_time,
       dst.update_time,
       du.user_id,
       du.user_name,
       du.email,
       du.phone_number,
       du.sex,
       du.avatar,
       du.status,
       du.loginIp,
       du.loginDate,
       du.signature,
       du.grade,
       du.experience,
       du.check_status,
       du.school_id,
       du.create_time,
       du.update_time,
       dur.user_role_id,
       dur.role_name,
       dur.user_id,
       dur.role_status,
       dur.create_time,
       dur.update_time,
       (select count(*) from dq_comment where dq_comment.article_id = da.article_id) as comment_num,
       (select count(*)
        from dq_collection
        where dq_collection.article_id = da.article_id)                              as collection_num
from dq_collection
         left join dq_article da on da.article_id = dq_collection.article_id
         left join dq_section ds on da.section_id = ds.section_id
         left join dq_section_type dst on da.section_type_id = dst.section_type_id
         left join dq_user du on da.author_id = du.user_id
         left join dq_user_role dur on du.user_id = dur.user_id