# 项目相关配置
dqframework:
  # 名称
  name: QuickDevelop
  # 版本
  version: 0.0.1
  # 版权年份
  copyrightYear: 2021
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/quickdevelop/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math


# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30


# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀（无前缀）
  pathMapping:

# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ar352878987
    # 这里使用mysql8(3306为mysql5.7.37 3307为mysql8)
    url: jdbc:mysql://localhost:3306/developq?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#    url: jdbc:mysql://localhost:3306/developq?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: ar352878987
    # 连接超时时间
    timeout: 1000s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

  # sa-token 配置
  sa-token:
    # token 名称(同时也是cookie的名称)
    token-name: maoyantoken
    # # token有效期，单位s 默认30天, -1代表永不过期
    timeout: -1
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: -1
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    allow-concurrent-login: false
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: true
    # token风格
    token-style: uuid
    # 是否输出操作日志
    is-log: false
    # 自定义的配置(权限注解开关)
    isOpen: true
  # 邮箱配置
  mail:
    username: 1071352028@qq.com
    # 不是密码而是授权码
    password: efyvcoaydydnbfii
    host: smtp.qq.com

my-sa-token:
  annotation: flase


up-load:
  proper:
    domain: "E:\\"


mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO
      select-strategy: not_empty
      insert-strategy: not_empty
      update-strategy: not_empty
  #      打印sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#应用监控
management:
  server:
    port: 9002
  endpoint:
    shutdown:
      enabled: true



